name: JohnBev
favicon: null
layout_spectrum: 0.31510746642015874
typography_spectrum: 0.15366843715310097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5044714547693729
  lightness: 0.6512571999337524
  saturation: 0.08824318740516901
  rhythmicContrast: 0.17481654835864902
purpose: []
